---
abstract: 'Base class for creating web interface'
author:
  - 'Sergei Svistunov <sergei-svistunov@yandex.ru>'
build_requires:
  FindBin: 0
  QBit::Application: 0
  Test::Deep: 0
  Test::More: 0
  URI::Escape: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: QBit-WebInterface
requires:
  CGI::Cookie: 0
  Digest::MD5: 0
  Exception: 0
  File::Path: 0
  LWP::UserAgent: 0
  POSIX: 0
  QBit::Application::Part: 0
  QBit::Class: 0
  Template: 2.20
  Template::Config: 0
  Template::Provider: 0
  base: 0
  qbit: 0
  strict: 0
version: 0.026
